# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'

  app-monitored-by-watchtower:
    image: malachivolta/shop2go-rest:release
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  app2-monitored-by-watchtower:
    image: malachivolta/shop2go-frontend:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - '80:80'

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=destroyerofworlds
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080
