name: Node.js CI with MongoDB

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable-dind
        options: --privileged # Required to run Docker inside Docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Compose
        run: |
          sudo service docker start
          docker-compose --version || (curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh)
          docker-compose --version

      - name: Start MongoDB
        run: |
          docker run -d --name mongodb -p 27017:27017 mongo:latest

      - name: Wait for MongoDB to start
        run: |
          timeout=0
          while [[ $timeout -lt 30 ]]; do
            if docker logs mongodb | grep -q 'waiting for connections on port'; then
              echo "MongoDB started successfully!"
              break
            fi
            echo "Waiting for MongoDB to start..."
            sleep 5
            timeout=$((timeout + 5))
          done
          docker ps -a

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.2"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Stop MongoDB
        run: docker stop mongodb
