name: Node.js Test

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.2"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
