name: Node.js CI with MongoDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo admin --eval 'db.runCommand({ ping: 1 })'" --health-interval 10s --health-timeout 10s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.2"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
